name: mohamedElgamalWeatherTask
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

 
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.6
  animated_splash_screen: ^1.0.1+2
  weather: ^1.2.4
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  page_view_indicators: ^1.3.1  
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/weather.PNG"
  adaptive_icon_background: "#FFFFFF"
  adapptive_icon_foreground: "assets/weather.PNG"

flutter:
  fonts:
    - family: VodafoneFontRg-Bold
      fonts:
        - asset: fonts/VodafoneRg-Bold.ttf
    
  
  uses-material-design: true
  assets:
    - assets/earth.jpg
    - assets/weather.PNG
   
    

  

